//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace WX2HK.MESWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MESWebserviceSoap", Namespace="http://tempuri.org/")]
    public partial class MESWebservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback MES_BomOperationCompleted;
        
        private System.Threading.SendOrPostCallback MES_Bom_orderOperationCompleted;
        
        private System.Threading.SendOrPostCallback MES_MatrialsListOperationCompleted;
        
        private System.Threading.SendOrPostCallback MES_MatrialsOperationCompleted;
        
        private System.Threading.SendOrPostCallback MES_MatrialsVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback MES_MatrialsVersion_orderOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MESWebservice() {
            this.Url = global::WX2HK.Properties.Settings.Default.WX2HK_MESWebService_MESWebservice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event MES_BomCompletedEventHandler MES_BomCompleted;
        
        /// <remarks/>
        public event MES_Bom_orderCompletedEventHandler MES_Bom_orderCompleted;
        
        /// <remarks/>
        public event MES_MatrialsListCompletedEventHandler MES_MatrialsListCompleted;
        
        /// <remarks/>
        public event MES_MatrialsCompletedEventHandler MES_MatrialsCompleted;
        
        /// <remarks/>
        public event MES_MatrialsVersionCompletedEventHandler MES_MatrialsVersionCompleted;
        
        /// <remarks/>
        public event MES_MatrialsVersion_orderCompletedEventHandler MES_MatrialsVersion_orderCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MES_Bom", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable MES_Bom(string cpCode) {
            object[] results = this.Invoke("MES_Bom", new object[] {
                        cpCode});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void MES_BomAsync(string cpCode) {
            this.MES_BomAsync(cpCode, null);
        }
        
        /// <remarks/>
        public void MES_BomAsync(string cpCode, object userState) {
            if ((this.MES_BomOperationCompleted == null)) {
                this.MES_BomOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMES_BomOperationCompleted);
            }
            this.InvokeAsync("MES_Bom", new object[] {
                        cpCode}, this.MES_BomOperationCompleted, userState);
        }
        
        private void OnMES_BomOperationCompleted(object arg) {
            if ((this.MES_BomCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MES_BomCompleted(this, new MES_BomCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MES_Bom_order", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable MES_Bom_order(string orderNo) {
            object[] results = this.Invoke("MES_Bom_order", new object[] {
                        orderNo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void MES_Bom_orderAsync(string orderNo) {
            this.MES_Bom_orderAsync(orderNo, null);
        }
        
        /// <remarks/>
        public void MES_Bom_orderAsync(string orderNo, object userState) {
            if ((this.MES_Bom_orderOperationCompleted == null)) {
                this.MES_Bom_orderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMES_Bom_orderOperationCompleted);
            }
            this.InvokeAsync("MES_Bom_order", new object[] {
                        orderNo}, this.MES_Bom_orderOperationCompleted, userState);
        }
        
        private void OnMES_Bom_orderOperationCompleted(object arg) {
            if ((this.MES_Bom_orderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MES_Bom_orderCompleted(this, new MES_Bom_orderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MES_MatrialsList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable MES_MatrialsList(string orderNo) {
            object[] results = this.Invoke("MES_MatrialsList", new object[] {
                        orderNo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void MES_MatrialsListAsync(string orderNo) {
            this.MES_MatrialsListAsync(orderNo, null);
        }
        
        /// <remarks/>
        public void MES_MatrialsListAsync(string orderNo, object userState) {
            if ((this.MES_MatrialsListOperationCompleted == null)) {
                this.MES_MatrialsListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMES_MatrialsListOperationCompleted);
            }
            this.InvokeAsync("MES_MatrialsList", new object[] {
                        orderNo}, this.MES_MatrialsListOperationCompleted, userState);
        }
        
        private void OnMES_MatrialsListOperationCompleted(object arg) {
            if ((this.MES_MatrialsListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MES_MatrialsListCompleted(this, new MES_MatrialsListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MES_Matrials", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable MES_Matrials(string cpCode) {
            object[] results = this.Invoke("MES_Matrials", new object[] {
                        cpCode});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void MES_MatrialsAsync(string cpCode) {
            this.MES_MatrialsAsync(cpCode, null);
        }
        
        /// <remarks/>
        public void MES_MatrialsAsync(string cpCode, object userState) {
            if ((this.MES_MatrialsOperationCompleted == null)) {
                this.MES_MatrialsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMES_MatrialsOperationCompleted);
            }
            this.InvokeAsync("MES_Matrials", new object[] {
                        cpCode}, this.MES_MatrialsOperationCompleted, userState);
        }
        
        private void OnMES_MatrialsOperationCompleted(object arg) {
            if ((this.MES_MatrialsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MES_MatrialsCompleted(this, new MES_MatrialsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MES_MatrialsVersion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable MES_MatrialsVersion(string cpCode) {
            object[] results = this.Invoke("MES_MatrialsVersion", new object[] {
                        cpCode});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void MES_MatrialsVersionAsync(string cpCode) {
            this.MES_MatrialsVersionAsync(cpCode, null);
        }
        
        /// <remarks/>
        public void MES_MatrialsVersionAsync(string cpCode, object userState) {
            if ((this.MES_MatrialsVersionOperationCompleted == null)) {
                this.MES_MatrialsVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMES_MatrialsVersionOperationCompleted);
            }
            this.InvokeAsync("MES_MatrialsVersion", new object[] {
                        cpCode}, this.MES_MatrialsVersionOperationCompleted, userState);
        }
        
        private void OnMES_MatrialsVersionOperationCompleted(object arg) {
            if ((this.MES_MatrialsVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MES_MatrialsVersionCompleted(this, new MES_MatrialsVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MES_MatrialsVersion_order", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable MES_MatrialsVersion_order(string orderNo) {
            object[] results = this.Invoke("MES_MatrialsVersion_order", new object[] {
                        orderNo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void MES_MatrialsVersion_orderAsync(string orderNo) {
            this.MES_MatrialsVersion_orderAsync(orderNo, null);
        }
        
        /// <remarks/>
        public void MES_MatrialsVersion_orderAsync(string orderNo, object userState) {
            if ((this.MES_MatrialsVersion_orderOperationCompleted == null)) {
                this.MES_MatrialsVersion_orderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMES_MatrialsVersion_orderOperationCompleted);
            }
            this.InvokeAsync("MES_MatrialsVersion_order", new object[] {
                        orderNo}, this.MES_MatrialsVersion_orderOperationCompleted, userState);
        }
        
        private void OnMES_MatrialsVersion_orderOperationCompleted(object arg) {
            if ((this.MES_MatrialsVersion_orderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MES_MatrialsVersion_orderCompleted(this, new MES_MatrialsVersion_orderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    public delegate void MES_BomCompletedEventHandler(object sender, MES_BomCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MES_BomCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MES_BomCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    public delegate void MES_Bom_orderCompletedEventHandler(object sender, MES_Bom_orderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MES_Bom_orderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MES_Bom_orderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    public delegate void MES_MatrialsListCompletedEventHandler(object sender, MES_MatrialsListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MES_MatrialsListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MES_MatrialsListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    public delegate void MES_MatrialsCompletedEventHandler(object sender, MES_MatrialsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MES_MatrialsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MES_MatrialsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    public delegate void MES_MatrialsVersionCompletedEventHandler(object sender, MES_MatrialsVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MES_MatrialsVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MES_MatrialsVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    public delegate void MES_MatrialsVersion_orderCompletedEventHandler(object sender, MES_MatrialsVersion_orderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MES_MatrialsVersion_orderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MES_MatrialsVersion_orderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591